// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3rME1QLGdIqz7nfp2MU3NoxXlH3jNHlA',
    appId: '1:457561814820:web:4cf704fa78af4d88e6a5b1',
    messagingSenderId: '457561814820',
    projectId: 'challengechef-6d284',
    authDomain: 'challengechef-6d284.firebaseapp.com',
    storageBucket: 'challengechef-6d284.firebasestorage.app',
    measurementId: 'G-0FDMHVNZ4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnhp_BS8mgTfN-Ev3dCcTHUnahY8DTxhg',
    appId: '1:457561814820:android:cbc09e9f9d0e1774e6a5b1',
    messagingSenderId: '457561814820',
    projectId: 'challengechef-6d284',
    storageBucket: 'challengechef-6d284.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtdreSEnvcqdCVI_OFIzJ7gOWSr-ZVKEY',
    appId: '1:457561814820:ios:99188824318d8ad6e6a5b1',
    messagingSenderId: '457561814820',
    projectId: 'challengechef-6d284',
    storageBucket: 'challengechef-6d284.firebasestorage.app',
    iosBundleId: 'com.example.challengechef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtdreSEnvcqdCVI_OFIzJ7gOWSr-ZVKEY',
    appId: '1:457561814820:ios:99188824318d8ad6e6a5b1',
    messagingSenderId: '457561814820',
    projectId: 'challengechef-6d284',
    storageBucket: 'challengechef-6d284.firebasestorage.app',
    iosBundleId: 'com.example.challengechef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3rME1QLGdIqz7nfp2MU3NoxXlH3jNHlA',
    appId: '1:457561814820:web:6efd84995b76224fe6a5b1',
    messagingSenderId: '457561814820',
    projectId: 'challengechef-6d284',
    authDomain: 'challengechef-6d284.firebaseapp.com',
    storageBucket: 'challengechef-6d284.firebasestorage.app',
    measurementId: 'G-BFV88066FT',
  );
}
