// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3jo7ARJjp0bWWQnT-vsAzIkxSpgN87Oo',
    appId: '1:795051969228:web:22007bc01e8b6eaa945069',
    messagingSenderId: '795051969228',
    projectId: 'challengechef-6232b',
    authDomain: 'challengechef-6232b.firebaseapp.com',
    storageBucket: 'challengechef-6232b.firebasestorage.app',
    measurementId: 'G-4DKC6GYV2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYAh_rGNH5YQ5ELMEgwon8FAYIkkP6u-w',
    appId: '1:795051969228:android:0f94323e0be05b8c945069',
    messagingSenderId: '795051969228',
    projectId: 'challengechef-6232b',
    storageBucket: 'challengechef-6232b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkmYsjek7XmbuSp_lPqq1oNUwK9Zknnd4',
    appId: '1:795051969228:ios:972627be462fe64b945069',
    messagingSenderId: '795051969228',
    projectId: 'challengechef-6232b',
    storageBucket: 'challengechef-6232b.firebasestorage.app',
    androidClientId: '795051969228-m1us13cp5m64fbvj0kbo3uhmkj20jbgm.apps.googleusercontent.com',
    iosClientId: '795051969228-9mmm13dbav8m0gu0deq0ihn51av4fj42.apps.googleusercontent.com',
    iosBundleId: 'com.example.challengechef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkmYsjek7XmbuSp_lPqq1oNUwK9Zknnd4',
    appId: '1:795051969228:ios:972627be462fe64b945069',
    messagingSenderId: '795051969228',
    projectId: 'challengechef-6232b',
    storageBucket: 'challengechef-6232b.firebasestorage.app',
    androidClientId: '795051969228-m1us13cp5m64fbvj0kbo3uhmkj20jbgm.apps.googleusercontent.com',
    iosClientId: '795051969228-9mmm13dbav8m0gu0deq0ihn51av4fj42.apps.googleusercontent.com',
    iosBundleId: 'com.example.challengechef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3jo7ARJjp0bWWQnT-vsAzIkxSpgN87Oo',
    appId: '1:795051969228:web:87042bdd8e37e881945069',
    messagingSenderId: '795051969228',
    projectId: 'challengechef-6232b',
    authDomain: 'challengechef-6232b.firebaseapp.com',
    storageBucket: 'challengechef-6232b.firebasestorage.app',
    measurementId: 'G-RKPDM4JDC2',
  );

}